version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    environment:
      - FHIR_BASE_URL=http://fhir:8080/
      - RATE_LIMIT_REQUESTS=1000
      - RATE_LIMIT_WINDOW=60
      - DATABASE_URL=sqlite:///local_ehr.db
      - NOTES_DB_PATH=local_ehr.db
      - DEBUG=true
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    depends_on:
      - fhir
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8006
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # FHIR Server (if not running locally)
  fhir:
    image: hapiproject/hapi:latest
    ports:
      - "8080:8080"
    environment:
      - hapi.fhir.allow_external_references=true
      - hapi.fhir.allow_placeholder_references=true
    volumes:
      - fhir_data:/hapi/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/fhir/metadata"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend_data:
  fhir_data:
