services:
  # Backend FHIR Proxy Service
  - type: web
    name: ehr-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000

  # Frontend Static Site
  - type: web
    name: ehr-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ehr-backend-87r9.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
