services:
  # Backend FHIR Proxy Service
  - type: web
    name: ehr-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8005
      - key: FHIR_BASE_URL
        value: https://fdfbc9a33dc5.ngrok-free.app/fhir
      - key: AUTO_SYNC_ON_STARTUP
        value: true
      - key: RAG_ENABLED
        value: true
      - key: RAG_STORE_PATH
        value: /data/chroma
      - key: RAG_EMBED_MODEL
        value: sentence-transformers/paraphrase-MiniLM-L6-v2
      - key: HF_HOME
        value: /data/hf_cache
    disk:
      name: ehr-backend-data
      mountPath: /data
      sizeGB: 5

  # Frontend Static Site
  - type: web
    name: ehr-frontend
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build:deploy
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ehr-backend-87r9.onrender.com  # Your Render backend URL
      - key: PUBLIC_URL
        value: /
      - key: DISABLE_ESLINT_PLUGIN
        value: true
      - key: CI
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
